### ISSUE TITLE
familytree - nodes are not centered after click on list

### ISSUE THREAD

**Issue by cool-Blue** [cool-Blue/SO-Questions#5]
The zoomTo function is called before the nodes have had a chance to settle in the middle of the graph.

**Comment by kwoxer** [comment]
Feels correct as it is right now. Sometimes it tries to rezoom again and again. But could be something with my slow PC. Maybe just setting the delay higher could help. But for me it's totally fine now =)

**Comment by cool-Blue** [comment]
No its by design but that can be adjusted in familytree-d3.js, I have a later version which is a little better because it does the first adjustment immediately...

``` js
      phasesAlpha = (function(){
        var p = [0.08, 0.04, 0.02, 0], i = null;
        return function (alpha){
          // resets if alpha is falsey or > p[0]
          var i0 = i;
          i = alpha ? (alpha > p[0] ? (i = 0) : i) : 0;
          if(alpha < (p[i])) i++;
          return i != i0;
        };
      })(), // fire the force_stage event when alpha reaches each value
```

If you want it to adjust less often, you can do this for example...

``` js
        var p = [0.04, 0]
```

This object is triggered in the tick function at this line...  

``` js
        if(phasesAlpha(e.alpha)) events.force_stage(e.alpha);
```

`force_stage` is one of the custom events I added to `familytree`, every time the alpha value of the force hits one of the numbers in the `p` array `phasesAlpha` returns `true` and so a `force_stage` event is triggered in the `tick` function (it resets automatically if alpha is greater than the first threshold value).  This event is subscribed to in the `merge` function in familytree.js so you can schedule asynchronous adjustments of the zoom center after selecting a node to focus on.  This is most important when you start from a blank graph and select from the list.  Without this feature, the graph will be centered on the random point where the force graph puts the new node which is likely to be off screen.

This new version above will trigger the first time it's called also so there is no delay on the first zoom.  I think its better.  

I won't close this yet until you decide about the next PR with this implemented.

**Comment by kwoxer** [comment]
Yes `var p = [0.04, 0]` is way better. Pushed it. You can close this here now. Thanks.

**Comment by cool-Blue** [comment]
Ok good, I hope you used the new version of phaseAlpha also. The one in my above comment. If not, I recommend you do, it eliminates the initial hesitation.
